### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [userjinha/c202309#2]
### 없는 파일
- challenge/week6/studentGrade.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week2/police
    - Error: expected ';' after expression [line 19]
        -  세미콜론이 없습니다.
- ERROR in challenge/week3/do-while_even
    - Error: use of undeclared identifier 'i로' [line 8]
         - 주석에 // 가 없어서 코드로 취급되고 있습니다. 수정해주세요.
- ERROR in challenge/week3/while_even
    - Error: use of undeclared identifier 'hello' [line 19]
         - 주석에 // 가 없어서 코드로 취급되고 있습니다. 수정해주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/choiceIf
    - Warning: using the result of an assignment as a condition without parentheses [line 17]
    - Warning: using the result of an assignment as a condition without parentheses [line 21]
    - Warning: using the result of an assignment as a condition without parentheses [line 25]
        - A와 B가 같은지를 체크하기 위해서는 "==" 을 써야합니다. "="를 쓰게 되면 변수에 값을 할당하는 것으로, 조건문에 들어가면 안됩니다.
- WARNING in challenge/week3/do-while_even
    - Warning: type specifier missing, defaults to 'int' [line 4]
         - main 함수에 반환형이 없습니다. 
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 7]
         - main 함수의 반환형은 int입니다. 반환형과 반환값을 추가해주세요.
    - Warning: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [line 8]
          - stdio.h 헤더파일이 없어서 printf 함수를 찾을 수 없습니다.  
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
         - main 함수의 반환형은 int입니다. 반환형과 반환값을 추가해주세요.
- WARNING in practice/week6/studentGrade
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 36]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 41]
        - scanf_s 함수를 사용해주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week2/police

**Comment by userjinha** [comment]
모두 수정하여 커밋 했습니다.
